# Generated by Django 2.2.1 on 2019-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Forums',
        ),
    ]
